# Generated by Django 3.0 on 2022-05-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('subcity', models.CharField(max_length=128)),
                ('wereda', models.IntegerField()),
                ('house_number', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=None, null=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('users', models.ManyToManyField(to='accounts.Client')),
            ],
        ),
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DeacesedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('nationality', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('subcity', models.CharField(max_length=128)),
                ('woreda', models.IntegerField()),
                ('house_number', models.IntegerField()),
                ('date_of_death', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ParentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MarriageCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_date', models.DateField()),
                ('verified', models.BooleanField(default=False)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CertificateDetails')),
                ('husband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husband', to='core.Spouse')),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wife', to='core.Spouse')),
            ],
        ),
        migrations.CreateModel(
            name='DeathCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('deacesed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deacesed_info', to='core.DeacesedInfo')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CertificateDetails')),
            ],
        ),
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15)),
                ('photo', models.ImageField(upload_to='')),
                ('verified', models.BooleanField(default=False)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CertificateDetails')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father', to='core.ParentInformation')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='core.ParentInformation')),
            ],
        ),
    ]
